### ISSUE TITLE
Use library versions

### ISSUE THREAD

**Issue by observant2** [maccam912/thewizzerofoz#1]
I just saw that the cargo.toml file contains:
```toml
[dependencies]
ggez = { git = "https://github.com/ggez/ggez" }
rand = "*"
find_folder = "*"
```
Meaning: "Always pull the newest version of every library". You should use constant versions, so your game won't break with new versions of ggez, rand and find_folder. :-)
